import { Recipe } from "./types";

// Testdata — erstattes med Supabase + Salling API
// Priser er pakkepris (hvad du betaler i kassen, ikke beregnet forbrug)
export const RECIPES: Recipe[] = [
  {
    id: "1",
    slug: "spaghetti-bolognese",
    title: "Spaghetti Bolognese",
    description: "Klassisk italiensk kødsauce med hakket oksekød og tomater.",
    servings: 4,
    estimatedTimeMinutes: 40,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    tags: ["kød"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i1", name: "Hakket oksekød 8–12%", isPantry: false },
        amount: 500, unit: "g",
        offerPrice: 62.95, offerStore: "Netto", normalPrice: 84.95,
        packageDesc: "500 g pakke",
      },
      {
        ingredient: { id: "i2", name: "Spaghetti", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 12.95,
        packageDesc: "500 g pakke",
      },
      {
        ingredient: { id: "i3", name: "Dåsetomater", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 8.95,
        packageDesc: "400 g dåse",
      },
      {
        ingredient: { id: "i4", name: "Løg", isPantry: false },
        amount: 2, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i5", name: "Hvidløg", isPantry: false },
        amount: 3, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i6", name: "Bouillonterninger", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 14.95,
        packageDesc: "10 stk pakke",
      },
      {
        ingredient: { id: "i7", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 2, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i8", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
      {
        ingredient: { id: "i9", name: "Oregano", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
    ],
  },
  {
    id: "2",
    slug: "kylling-karry",
    title: "Kylling i karry",
    description: "Cremet kyllingeret med kokosmælk og karry — klar på 30 minutter.",
    servings: 4,
    estimatedTimeMinutes: 30,
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    tags: ["kød"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i10", name: "Kyllingefilet", isPantry: false },
        amount: 600, unit: "g",
        offerPrice: 42.95, offerStore: "Føtex", normalPrice: 59.95,
        packageDesc: "600 g pakke",
      },
      {
        ingredient: { id: "i11", name: "Kokosmælk", isPantry: false },
        amount: 400, unit: "ml",
        offerPrice: 14.95, offerStore: "Netto", normalPrice: 19.95,
        packageDesc: "400 ml dåse",
      },
      {
        ingredient: { id: "i12", name: "Ris", isPantry: false },
        amount: 300, unit: "g",
        normalPrice: 16.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i13", name: "Løg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i14", name: "Hvidløg", isPantry: false },
        amount: 2, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i15", name: "Karrypasta (gul)", isPantry: false },
        amount: 2, unit: "spsk",
        normalPrice: 24.95,
        packageDesc: "100 g glas",
      },
      {
        ingredient: { id: "i16", name: "Rapsolie", isPantry: true, estimatedPantryPrice: 22 },
        amount: 1, unit: "spsk",
        packageDesc: "1 liter flaske",
      },
      {
        ingredient: { id: "i17", name: "Salt", isPantry: true, estimatedPantryPrice: 8 },
        amount: 1, unit: "tsk",
        packageDesc: "750 g pakke",
      },
    ],
  },
  {
    id: "3",
    slug: "linsesuppe",
    title: "Rød linsesuppe",
    description: "Fyldig vegetarsuppe med røde linser, gulerødder og spidskommen.",
    servings: 4,
    estimatedTimeMinutes: 35,
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: true,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i18", name: "Røde linser", isPantry: false },
        amount: 300, unit: "g",
        offerPrice: 16.95, offerStore: "Netto", normalPrice: 24.95,
        packageDesc: "500 g pose",
      },
      {
        ingredient: { id: "i19", name: "Gulerødder", isPantry: false },
        amount: 3, unit: "stk",
        offerPrice: 8.95, offerStore: "Netto", normalPrice: 14.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i20", name: "Dåsetomater", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 8.95,
        packageDesc: "400 g dåse",
      },
      {
        ingredient: { id: "i21", name: "Løg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i22", name: "Hvidløg", isPantry: false },
        amount: 2, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i23", name: "Grøntsagsbouillon", isPantry: false },
        amount: 1, unit: "terning",
        normalPrice: 14.95,
        packageDesc: "10 stk pakke",
      },
      {
        ingredient: { id: "i24", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 1, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i25", name: "Spidskommen", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
      {
        ingredient: { id: "i26", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "4",
    slug: "grontsagswok",
    title: "Grøntsagswok med nudler",
    description: "Hurtig og farverig wok med sæsonens grøntsager og nudler.",
    servings: 2,
    estimatedTimeMinutes: 20,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: false,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i27", name: "Ægnudler", isPantry: false },
        amount: 200, unit: "g",
        offerPrice: 12.95, offerStore: "Netto", normalPrice: 18.95,
        packageDesc: "300 g pakke",
      },
      {
        ingredient: { id: "i28", name: "Broccoli", isPantry: false },
        amount: 300, unit: "g",
        offerPrice: 14.95, offerStore: "Føtex", normalPrice: 22.95,
        packageDesc: "ca. 400 g hoved",
      },
      {
        ingredient: { id: "i29", name: "Peberfrugt", isPantry: false },
        amount: 2, unit: "stk",
        offerPrice: 9.95, offerStore: "Netto", normalPrice: 15.95,
        packageDesc: "2 stk",
      },
      {
        ingredient: { id: "i30", name: "Sojasauce", isPantry: false },
        amount: 3, unit: "spsk",
        normalPrice: 18.95,
        packageDesc: "150 ml flaske",
      },
      {
        ingredient: { id: "i31", name: "Hvidløg", isPantry: false },
        amount: 2, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i32", name: "Ingefær (frisk)", isPantry: false },
        amount: 1, unit: "cm",
        normalPrice: 9.95,
        packageDesc: "ca. 100 g rod",
      },
      {
        ingredient: { id: "i33", name: "Sesamolie", isPantry: true, estimatedPantryPrice: 32 },
        amount: 1, unit: "tsk",
        packageDesc: "250 ml flaske",
      },
    ],
  },
  {
    id: "5",
    slug: "ovnbagt-torsk",
    title: "Ovnbagt torsk med kartofler",
    description: "Enkel og sund ovnret med torsk, kartofler og citron.",
    servings: 4,
    estimatedTimeMinutes: 45,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
    tags: ["fisk"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i34", name: "Torskefilet", isPantry: false },
        amount: 600, unit: "g",
        offerPrice: 54.95, offerStore: "Føtex", normalPrice: 74.95,
        packageDesc: "600 g pakke",
      },
      {
        ingredient: { id: "i35", name: "Kartofler", isPantry: false },
        amount: 800, unit: "g",
        offerPrice: 12.95, offerStore: "Netto", normalPrice: 19.95,
        packageDesc: "1,5 kg pose",
      },
      {
        ingredient: { id: "i36", name: "Citron", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 5.95,
        packageDesc: "1 stk",
      },
      {
        ingredient: { id: "i37", name: "Cherry-tomater", isPantry: false },
        amount: 250, unit: "g",
        normalPrice: 16.95,
        packageDesc: "250 g bakke",
      },
      {
        ingredient: { id: "i38", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 3, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i39", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
      {
        ingredient: { id: "i40", name: "Timian", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
    ],
  },
  {
    id: "6",
    slug: "kikertegryde",
    title: "Kikertegryde med spinat",
    description: "Mættende vegetarret med kikærter, spinat og krydret tomatsovs.",
    servings: 4,
    estimatedTimeMinutes: 25,
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: true,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i41", name: "Kikærter", isPantry: false },
        amount: 800, unit: "g",
        offerPrice: 14.95, offerStore: "Netto", normalPrice: 21.90,
        packageDesc: "2 x 400 g dåser",
      },
      {
        ingredient: { id: "i42", name: "Frisk spinat", isPantry: false },
        amount: 200, unit: "g",
        offerPrice: 16.95, offerStore: "Føtex", normalPrice: 24.95,
        packageDesc: "200 g pose",
      },
      {
        ingredient: { id: "i43", name: "Dåsetomater", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 8.95,
        packageDesc: "400 g dåse",
      },
      {
        ingredient: { id: "i44", name: "Løg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i45", name: "Hvidløg", isPantry: false },
        amount: 3, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i46", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 2, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i47", name: "Spidskommen", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
      {
        ingredient: { id: "i48", name: "Paprika", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
      {
        ingredient: { id: "i49", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  // === 9 nye opskrifter ===
  {
    id: "7",
    slug: "pasta-pesto-tomater",
    title: "Pasta med pesto og cherry-tomater",
    description: "Hurtig og lækker pasta med frisk basilikumpesto og søde cherry-tomater.",
    servings: 4,
    estimatedTimeMinutes: 20,
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: false,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i50", name: "Penne pasta", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 11.95,
        packageDesc: "500 g pakke",
      },
      {
        ingredient: { id: "i51", name: "Pestosauce (basilikum)", isPantry: false },
        amount: 190, unit: "g",
        offerPrice: 19.95, offerStore: "Rema 1000", normalPrice: 28.95,
        packageDesc: "190 g glas",
      },
      {
        ingredient: { id: "i52", name: "Cherry-tomater", isPantry: false },
        amount: 250, unit: "g",
        normalPrice: 16.95,
        packageDesc: "250 g bakke",
      },
      {
        ingredient: { id: "i53", name: "Frisk parmesan", isPantry: false },
        amount: 50, unit: "g",
        normalPrice: 24.95,
        packageDesc: "100 g stykke",
      },
      {
        ingredient: { id: "i54", name: "Hvidløg", isPantry: false },
        amount: 2, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i55", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 2, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i56", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "8",
    slug: "hakkebof-kartoffelmos",
    title: "Hakkebøf med kartoffelmos",
    description: "Dansk klassiker med saftige hakkebøffer og cremet kartoffelmos.",
    servings: 4,
    estimatedTimeMinutes: 40,
    imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80",
    tags: ["kød"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i57", name: "Hakket oksekød 15–18%", isPantry: false },
        amount: 600, unit: "g",
        offerPrice: 54.95, offerStore: "Rema 1000", normalPrice: 74.95,
        packageDesc: "600 g pakke",
      },
      {
        ingredient: { id: "i58", name: "Kartofler", isPantry: false },
        amount: 1000, unit: "g",
        normalPrice: 14.95,
        packageDesc: "1,5 kg pose",
      },
      {
        ingredient: { id: "i59", name: "Smør", isPantry: false },
        amount: 50, unit: "g",
        normalPrice: 18.95,
        packageDesc: "200 g pakke",
      },
      {
        ingredient: { id: "i60", name: "Sødmælk", isPantry: false },
        amount: 100, unit: "ml",
        normalPrice: 9.95,
        packageDesc: "1 liter karton",
      },
      {
        ingredient: { id: "i61", name: "Løg", isPantry: false },
        amount: 2, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i62", name: "Rapsolie", isPantry: true, estimatedPantryPrice: 22 },
        amount: 2, unit: "spsk",
        packageDesc: "1 liter flaske",
      },
      {
        ingredient: { id: "i63", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "9",
    slug: "aeggestegte-ris",
    title: "Æggestegte ris med grøntsager",
    description: "Asiatisk inspireret vegetarret med ris, æg og friske grøntsager.",
    servings: 4,
    estimatedTimeMinutes: 25,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: false,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i64", name: "Ris (langtkornet)", isPantry: false },
        amount: 300, unit: "g",
        normalPrice: 16.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i65", name: "Æg", isPantry: false },
        amount: 4, unit: "stk",
        offerPrice: 14.95, offerStore: "Netto", normalPrice: 19.95,
        packageDesc: "10 stk bakke",
      },
      {
        ingredient: { id: "i66", name: "Gulerødder", isPantry: false },
        amount: 2, unit: "stk",
        normalPrice: 14.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i67", name: "Peberfrugt", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 9.95,
        packageDesc: "1 stk",
      },
      {
        ingredient: { id: "i68", name: "Forårsløg", isPantry: false },
        amount: 4, unit: "stk",
        normalPrice: 8.95,
        packageDesc: "1 bdt",
      },
      {
        ingredient: { id: "i69", name: "Sojasauce", isPantry: false },
        amount: 3, unit: "spsk",
        normalPrice: 18.95,
        packageDesc: "150 ml flaske",
      },
      {
        ingredient: { id: "i70", name: "Rapsolie", isPantry: true, estimatedPantryPrice: 22 },
        amount: 2, unit: "spsk",
        packageDesc: "1 liter flaske",
      },
      {
        ingredient: { id: "i71", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "10",
    slug: "laks-asparges-ris",
    title: "Laks med asparges og ris",
    description: "Saftig laks serveret med grønne asparges og dampede ris.",
    servings: 4,
    estimatedTimeMinutes: 35,
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    tags: ["fisk"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i72", name: "Laksefilet", isPantry: false },
        amount: 600, unit: "g",
        offerPrice: 79.95, offerStore: "Føtex", normalPrice: 99.95,
        packageDesc: "600 g pakke",
      },
      {
        ingredient: { id: "i73", name: "Grønne asparges", isPantry: false },
        amount: 500, unit: "g",
        offerPrice: 24.95, offerStore: "Rema 1000", normalPrice: 34.95,
        packageDesc: "500 g bdt",
      },
      {
        ingredient: { id: "i74", name: "Ris", isPantry: false },
        amount: 300, unit: "g",
        normalPrice: 16.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i75", name: "Citron", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 5.95,
        packageDesc: "1 stk",
      },
      {
        ingredient: { id: "i76", name: "Smør", isPantry: false },
        amount: 30, unit: "g",
        normalPrice: 18.95,
        packageDesc: "200 g pakke",
      },
      {
        ingredient: { id: "i77", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 2, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i78", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "11",
    slug: "tomatsuppe-flode",
    title: "Tomatsuppe med fløde",
    description: "Varm og silkeblød tomatsuppe med fløde og friske krydderurter.",
    servings: 4,
    estimatedTimeMinutes: 30,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: true,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i79", name: "Dåsetomater (hakkede)", isPantry: false },
        amount: 800, unit: "g",
        offerPrice: 14.95, offerStore: "Netto", normalPrice: 19.90,
        packageDesc: "2 x 400 g dåser",
      },
      {
        ingredient: { id: "i80", name: "Piskefløde", isPantry: false },
        amount: 200, unit: "ml",
        normalPrice: 14.95,
        packageDesc: "200 ml karton",
      },
      {
        ingredient: { id: "i81", name: "Løg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i82", name: "Hvidløg", isPantry: false },
        amount: 3, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i83", name: "Grøntsagsbouillon", isPantry: false },
        amount: 1, unit: "terning",
        normalPrice: 14.95,
        packageDesc: "10 stk pakke",
      },
      {
        ingredient: { id: "i84", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 2, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i85", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
      {
        ingredient: { id: "i86", name: "Sukker", isPantry: true, estimatedPantryPrice: 8 },
        amount: 1, unit: "tsk",
        packageDesc: "1 kg pose",
      },
    ],
  },
  {
    id: "12",
    slug: "kyllingelaar-rodfrugter",
    title: "Kyllingelår med rodfrugter",
    description: "Saftige kyllingelår ovnstegt med gulerødder, pastinakker og selleri.",
    servings: 4,
    estimatedTimeMinutes: 60,
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=800&q=80",
    tags: ["kød"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i87", name: "Kyllingelår", isPantry: false },
        amount: 1200, unit: "g",
        offerPrice: 49.95, offerStore: "Rema 1000", normalPrice: 65.95,
        packageDesc: "4 stk pakke ~1,2 kg",
      },
      {
        ingredient: { id: "i88", name: "Gulerødder", isPantry: false },
        amount: 400, unit: "g",
        normalPrice: 14.95,
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i89", name: "Pastinakker", isPantry: false },
        amount: 300, unit: "g",
        normalPrice: 12.95,
        packageDesc: "løsvægt ca. 300 g",
      },
      {
        ingredient: { id: "i90", name: "Selleri (stykke)", isPantry: false },
        amount: 200, unit: "g",
        normalPrice: 11.95,
        packageDesc: "ca. 1/4 rod",
      },
      {
        ingredient: { id: "i91", name: "Løg", isPantry: false },
        amount: 2, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i92", name: "Hvidløg", isPantry: false },
        amount: 4, unit: "fed",
        normalPrice: 7.95,
        packageDesc: "3 hoveder",
      },
      {
        ingredient: { id: "i93", name: "Olivenolie", isPantry: true, estimatedPantryPrice: 28 },
        amount: 3, unit: "spsk",
        packageDesc: "75 cl flaske",
      },
      {
        ingredient: { id: "i94", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
      {
        ingredient: { id: "i95", name: "Timian", isPantry: true, estimatedPantryPrice: 15 },
        amount: 1, unit: "tsk",
        packageDesc: "lille krydderiglas",
      },
    ],
  },
  {
    id: "13",
    slug: "bønnetacos",
    title: "Bønnetacos",
    description: "Smørbare bønner i sprøde tacoskaller med friske grøntsager og salsa.",
    servings: 4,
    estimatedTimeMinutes: 25,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: false,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i96", name: "Tacoskaller (12 stk)", isPantry: false },
        amount: 12, unit: "stk",
        offerPrice: 12.95, offerStore: "Netto", normalPrice: 18.95,
        packageDesc: "12 stk pakke",
      },
      {
        ingredient: { id: "i97", name: "Sorte bønner (dåse)", isPantry: false },
        amount: 800, unit: "g",
        normalPrice: 15.90,
        packageDesc: "2 x 400 g dåser",
      },
      {
        ingredient: { id: "i98", name: "Salsa (mild)", isPantry: false },
        amount: 340, unit: "g",
        normalPrice: 22.95,
        packageDesc: "340 g glas",
      },
      {
        ingredient: { id: "i99", name: "Cheddarost revet", isPantry: false },
        amount: 100, unit: "g",
        normalPrice: 22.95,
        packageDesc: "200 g pose",
      },
      {
        ingredient: { id: "i100", name: "Romaine salat", isPantry: false },
        amount: 1, unit: "hoved",
        normalPrice: 11.95,
        packageDesc: "1 hoved",
      },
      {
        ingredient: { id: "i101", name: "Tacokrydderi", isPantry: true, estimatedPantryPrice: 12 },
        amount: 1, unit: "pose",
        packageDesc: "40 g pose",
      },
      {
        ingredient: { id: "i102", name: "Rapsolie", isPantry: true, estimatedPantryPrice: 22 },
        amount: 1, unit: "spsk",
        packageDesc: "1 liter flaske",
      },
    ],
  },
  {
    id: "14",
    slug: "frikadeller-persillesovs",
    title: "Frikadeller med persillesovs",
    description: "Klassiske danske frikadeller med cremet persillesovs og kogte kartofler.",
    servings: 4,
    estimatedTimeMinutes: 45,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    tags: ["kød"],
    isOkologisk: false,
    isVegetarisk: false,
    isDansk: true,
    ingredients: [
      {
        ingredient: { id: "i103", name: "Hakket svinekød (8%)", isPantry: false },
        amount: 500, unit: "g",
        offerPrice: 34.95, offerStore: "Rema 1000", normalPrice: 44.95,
        packageDesc: "500 g pakke",
      },
      {
        ingredient: { id: "i104", name: "Kartofler", isPantry: false },
        amount: 800, unit: "g",
        normalPrice: 14.95,
        packageDesc: "1,5 kg pose",
      },
      {
        ingredient: { id: "i105", name: "Piskefløde", isPantry: false },
        amount: 200, unit: "ml",
        normalPrice: 14.95,
        packageDesc: "200 ml karton",
      },
      {
        ingredient: { id: "i106", name: "Frisk persille", isPantry: false },
        amount: 1, unit: "bdt",
        normalPrice: 9.95,
        packageDesc: "1 bdt",
      },
      {
        ingredient: { id: "i107", name: "Løg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 12.95,
        packageDesc: "1 kg pose (~8 stk)",
      },
      {
        ingredient: { id: "i108", name: "Æg", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 19.95,
        packageDesc: "10 stk bakke",
      },
      {
        ingredient: { id: "i109", name: "Smør", isPantry: true, estimatedPantryPrice: 18 },
        amount: 50, unit: "g",
        packageDesc: "200 g pakke",
      },
      {
        ingredient: { id: "i110", name: "Mel", isPantry: true, estimatedPantryPrice: 12 },
        amount: 2, unit: "spsk",
        packageDesc: "1 kg pose",
      },
      {
        ingredient: { id: "i111", name: "Salt & peber", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "knivspids",
        packageDesc: "efter smag",
      },
    ],
  },
  {
    id: "15",
    slug: "jordnoeddenudle-tofu",
    title: "Jordnøddenudle med tofu",
    description: "Cremede nudler i jordnøddedressing med sprød tofu og friske grøntsager.",
    servings: 4,
    estimatedTimeMinutes: 30,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80",
    tags: ["vegetar"],
    isOkologisk: false,
    isVegetarisk: true,
    isDansk: false,
    ingredients: [
      {
        ingredient: { id: "i112", name: "Fast tofu", isPantry: false },
        amount: 400, unit: "g",
        offerPrice: 19.95, offerStore: "Føtex", normalPrice: 27.95,
        packageDesc: "400 g pakke",
      },
      {
        ingredient: { id: "i113", name: "Risnudler", isPantry: false },
        amount: 200, unit: "g",
        normalPrice: 14.95,
        packageDesc: "250 g pakke",
      },
      {
        ingredient: { id: "i114", name: "Jordnøddesmør", isPantry: false },
        amount: 4, unit: "spsk",
        normalPrice: 24.95,
        packageDesc: "340 g glas",
      },
      {
        ingredient: { id: "i115", name: "Sojasauce", isPantry: false },
        amount: 3, unit: "spsk",
        normalPrice: 18.95,
        packageDesc: "150 ml flaske",
      },
      {
        ingredient: { id: "i116", name: "Forårsløg", isPantry: false },
        amount: 4, unit: "stk",
        normalPrice: 8.95,
        packageDesc: "1 bdt",
      },
      {
        ingredient: { id: "i117", name: "Agurk", isPantry: false },
        amount: 1, unit: "stk",
        normalPrice: 9.95,
        packageDesc: "1 stk",
      },
      {
        ingredient: { id: "i118", name: "Sesamolie", isPantry: true, estimatedPantryPrice: 32 },
        amount: 2, unit: "tsk",
        packageDesc: "250 ml flaske",
      },
      {
        ingredient: { id: "i119", name: "Ingefær (frisk)", isPantry: true, estimatedPantryPrice: 10 },
        amount: 1, unit: "cm",
        packageDesc: "ca. 100 g rod",
      },
      {
        ingredient: { id: "i120", name: "Hvidløg", isPantry: true, estimatedPantryPrice: 8 },
        amount: 2, unit: "fed",
        packageDesc: "3 hoveder",
      },
    ],
  },
];
